services:
    migrate:
      image: 'migrate/migrate'

      container_name: migrate

      command: ["-path", "/migrations", "-database", "postgresql://postgres:my_password@localhost:5432/testPPTgBotDB?sslmode=disable", "up", "1"]

      network_mode: container:postgres

      volumes:
          - ./migrations/postgres:/migrations
